/* This file is auto-generated by a tool */
if (!String.prototype.format) {
  String.prototype.format = function() {
    var args = arguments;
    return this.replace(/{(\d+)}/g, function(match, number) {
      return typeof args[number] != 'undefined'
        ? args[number]
        : match
      ;
    });
  };
}
var Localization = Localization || {};
Localization.AddUsers = {
  'NotifyErrorInvitationCanBeResentOnlyToUsersWithEmails': 'E-posti aadressita kasutajatele kutset ei saa saata.',
  'UserHasEKoolAndStuudiumBinding': 'Kasutajal on eKooli ja Stuudiumi liidestus',
  'NotifyErrorChooseMembersToRemove': 'Märgi kasutajad, keda nimekirjast eemaldada!',
  'NotifyErrorInvitationWasResentOnlyToUsersWithEmails': 'Kutse saadeti ainult e-posti aadressiga kasutajatele.',
  'NotifyWarningNoUsersAdded': 'Kasutajaid ei lisatud!',
  'UserHasStuudiumBinding': 'Kasutajal on Stuudiumi liidestus',
  'ValidationErrorWrongEmail': 'Kontrolli e-posti aadressi. Lubatud on ladina tähestiku sümbolid.',
  'NotifyErrorChooseMembersToResendInvitation': 'Märgi kasutajad, kellele kutse uuesti saata!',
  'UserHasEKoolBinding': 'Kasutajal on eKooli liidestus',
  'ErrorChooseStudents': 'Vali õpilased!',
  'ValidationErrorFormMustHaveFilledRows': 'Ühel real peavad kõik väljad täidetud olema!',
};
Localization.AdminCustomerUsers = {
  'ModalTitle': 'Kasutajalt eemaldatakse roll „{0}“.',
};
Localization.AdminUsersSearch = {
  'EnterSchoolNameMessage': 'Sisesta kooli nimi',
  'LicensePackageAll': 'Kõik paketid',
};
Localization.Annotation = {
  'ErrorMessageAnnotationAlreadyDeleted': 'Annotatsiooni muutmine ebaõnnestus, sest see oli juba kustutatud.',
};
Localization.AutoComplete = {
  'SearchingMessage': 'Otsin…',
  'ErrorLoadingResultsMessage': 'Tulemuste laadimine ebaõnnestus',
  'NoResultsMessage': 'Ei leitud tulemusi',
};
Localization.ChapterExerciseCreate = {
  'NotifyErrorMandatoryChapter': 'Peatükk peab olema valitud!',
  'NotifyErrorMandatoryTitle': 'Pealkiri peab olema määratud!',
  'NotifyErrorMandatoryKit': 'Õppekomplekt peab olema valitud!',
};
Localization.ChapterExercisesIndex = {
  'TooltipTextUserNotInActiveRegisters': 'Töö koostamiseks peab Sul olema vähemalt üks päevik.',
  'ConfimationDialogAreYouSure': 'Kas oled kindel, et soovid seda teha?',
};
Localization.ChapterIndex = {
  'LinkCopiedSuccessMessage': 'Link on kopeeritud.',
};
Localization.CouponBatchDetails = {
  'DeleteCouponModalMessage': 'Kinkekaart kustutatakse. Kui kinkekaart on juba kliendini jõudnud, siis pärast kustutamist ei saa ta seda enam kasutada.',
};
Localization.CouponCreate = {
  'EnterCustomerNameMessage': 'Sisesta kliendi nimi',
  'PricePerMonthFormat': '{0} kuu',
  'CustomerTypeSchool': 'Kool',
  'WarningCouponCountBigFormat': 'Kas oled kindel, et soovid luua {0} kinkekaarti?',
  'QuantityMustBeSetError': 'Kogus peab olema sisestatud.',
  'NoResultsMessage': 'Tulemusi ei leitud',
  'CouponCountMustBeSetError': 'Kinkekaartide arv peab olema sisestatud.',
  'PackageMustBeSelectedError': 'Pakett peab olema valitud.',
  'CouponValidUntilMustBeSetError': 'Kinkekaardi kehtivuse lõpp peab olema valitud.',
  'CustomerTypeMustBeSelectedError': 'Kliendi tüüp peab olema valitud.',
  'SelectCustomerTypeError': 'Vali kõigepealt kliendi tüüp.',
  'CustomerTypePrivateUser': 'Eraklient',
  'LengthOfValidityMustBeSetError': 'Kehtivuse pikkus peab olema sisestatud.',
};
Localization.CreateCustomer = {
  'NoCustomerTypeSelectedError': 'Kliendi tüüp peab olema valitud.',
};
Localization.CreateSchoolAdminAccount = {
  'PasswordRepeatDifferentError': 'Salasõna ja salasõna kordus ei lange kokku.',
  'RequiredFieldLeftEmptyErrorWithArgs': '{0} peab olema täidetud.',
  'Field': 'Väli',
  'PasswordTooShortErrorWithArgs': 'Salasõna peab olema vähemalt {0} sümbolit pikk.',
  'UserNameInvalidEmailWithArgs': '{0} peab olema korrektse e-posti aadressi formaadis.',
};
Localization.Currency = {
  'CurrencyFormatDefault': '{0} {1}',
};
Localization.EditTextExercise = {
  'NeededSpaceRemoval': 'Jäetud kokku kirjutamata',
  'PerformedRemoval': '{0} kustutatud {1}',
  'NeededSpaceAddition': 'Jäetud lahku kirjutamata',
  'PerformedSpaceRemoval': '{0} kokku kirjutatud',
  'NeededRemoval': 'Jäetud kustutamata {0}',
  'ExpectedClause': '; peaks olema {0}',
  'NeededReplacement': 'Jäetud parandamata <i>{0} → {1}</i>',
  'EvaluationCorrectly': 'Õigesti',
  'PerformedSpaceAddition': '{0} lahku kirjutatud',
  'EvaluationIncorrectly': 'Valesti',
  'NeededAddition': 'Jäetud lisamata {0}',
  'PerformedAddition': '{0} lisatud {1}',
  'PerformedReplacement': '{0} parandatud <i>{1} → {2}</i>',
};
Localization.ErrorReportModal = {
  'ErrorReportContactInfoExcessiveLength': 'Kontaktandmeid võid sisestada kuni {0} sümbolit, oled sisestanud {1} sümbolit.',
  'AddErrorDescription': 'Sisesta vea kirjeldus!',
  'ErrorReportDescriptionExcessiveLength': 'Vea kirjeldus võib olla kuni {0} sümbolit pikk, oled sisestanud {1} sümbolit.',
  'ErrorReportCreated': 'Teavitus salvestatud',
};
Localization.ExerciseMenu = {
  'ExerciseToolTipText': 'Töö ülesanded',
  'ChapterExerciseToolTipText': 'Peatüki ülesanded',
};
Localization.Exercises = {
  'DragFromGroupTitle': 'Lohista vastus siit sobivasse veergu',
  'ChangeButtonText': 'Muuda',
  'DragHerePlaceholder': 'lohista siia',
  'SaveButtonText': 'Salvesta',
  'TeachersCommentHeading': 'Õpetaja {0} kommentaar',
  'CheckAnswerButtonText': 'Kontrolli vastust',
  'NoAnswerSelectedByStudent': 'Õpilane jättis vastuse valimata',
  'ButtonTextShowMyAnswers': 'Näita minu vastuseid',
  'MethodologicalTextSectionHeading': 'NB! Õpilased seda sisuühikut ei näe.',
  'ButtonTextShowStudentsAnswers': 'Näita õpilase vastuseid',
  'FixMistakesButtonText': 'Muuda vastust',
  'ExerciseOldCommentWarning': 'See on vana kommentaar õpetajalt {0}. Kas oled kindel, et soovid selle kommentaari uuesti saata?',
  'HideExampleAnswersText': 'Peida näidisvastus',
  'TryAgainButtonText': 'Alusta uuesti',
  'NoAnswerSelectedByYou': 'Jätsid vastuse valimata',
};
Localization.FoxGraph = {
  'ButtonTextLoad': 'Laadi',
};
Localization.Global = {
  'SavedNotificationMessage': 'Salvestatud',
  'LoadingContentMessage': 'Laadin sisu…',
  'AjaxErrorSessionExpired': 'Kasutaja sessioon on aegunud!',
  'AjaxErrorNoAccess': 'Kasutajal puudub ligipääs antud ressursile!',
  'AjaxErrorSessionChanged': 'Kasutaja sessioon on vahepeal muutunud, palun värskendage lehte!',
  'AjaxErrorNoConnection': 'Puudub ühendus serveriga!',
  'DatepickerLanguageCode': 'et',
  'ConfirmationModalQuestion': 'Kas oled kindel, et soovid seda teha?',
  'AjaxErrorConcurrency': 'Andmed on vahepeal uuenenud, palun värskendage lehte!',
  'AjaxErrorOther': 'Midagi läks valesti :(',
};
Localization.InvoiceRecipient = {
  'ConfirmClearInvoiceRecipientText': 'Kas soovid arve saaja andmed kustutada?',
};
Localization.JoinRegister = {
  'SuccessfullyJoinedRegister': 'Liitusid päevikuga!',
};
Localization.JoinSchool = {
  'SuccessfullyJoinedSchool': 'Liitusid kooliga!',
};
Localization.KitAddKitToRegisters = {
  'ChooseRegistersPlaceholder': 'Vali',
  'NotifySuccessMessageAddedToSingleRegister': 'Õppekomplekt lisati päevikule',
  'NotifySuccessMessageAddedToMultipleRegisters': 'Õppekomplekt lisati päevikutele',
};
Localization.KitCreateRegisterFromKit = {
  'NotifyErrorMessageDataNotSaved': 'Andmete salvestamine ebaõnnestus!',
  'ErrorMessageTeacherNotFound': 'Õpetajat ei leitud, vali õpetaja loetelust!',
  'NotifySuccessMessageDataSaved': 'Andmed on salvestatud!',
};
Localization.KitDetails = {
  'InUseSingleRegister': 'Kasutusel 1 päevikus',
  'InUseRegisters': 'Kasutusel {0} päevikus',
  'RemoveSuccessMessage': 'Teos on õppematerjali hulgast eemaldatud.',
};
Localization.LicensingIndex = {
  'LicenseButtonLicenseNUsersText': 'Litsentseeri {0} kasutajat',
  'LicenseButtonLicenseOneUserText': 'Litsentseeri 1 kasutaja',
  'LicenseButtonText': 'Litsentseeri',
  'LicenseSelectionPlaceHolder': 'Soovi korral vali litsents',
};
Localization.LicensingRemoveLicenses = {
  'ButtonRemoveLicenseNUsersText': 'Eemalda litsents {0} kasutajalt',
  'LicenseMissing': 'litsents puudub',
  'RemoveLicenseButtonText': 'Eemalda',
  'ButtonTooltipNoLicenseSelected': 'Litsentsi eemaldamiseks tuleb valida litsents, mis kasutajatel juba on',
  'ChosenLicenseMissing': 'valitud litsents puudub',
  'ButtonTooltipNoUsersSelected': 'Litsentsi eemaldamiseks tuleb kõigepealt valida kasutajad, kellelt litsents eemaldada',
  'LicenseSelectionPlaceHolder': 'Soovi korral vali litsents',
};
Localization.ManageIndex = {
  'ConfirmationDialog': 'Kas oled kindel, et soovid seda teha?',
};
Localization.ManageLinkLoginConfirmation = {
  'ConfirmationDialog': 'Kas oled kindel, et soovid seda teha?',
};
Localization.MediaGallery = {
  'ExitFullscreen': 'Välju täisekraanilt',
  'SendToProjector': 'Saada projektorisse',
  'ShowFullscreen': 'Näita täisekraanil',
};
Localization.OrderDetails = {
  'ConfirmationModalMessage': 'Kas oled kindel, et soovid seda teha?',
  'ReturnToDraftModalBoxTip': 'Tellimus avatakse, kool saab tellimust muuta ja uuesti kinnitada.',
  'OrderWillBeConfirmedBoxTip': 'Tellimus kinnitatakse.',
  'ActionFailedMessage': 'Tegevus ei õnnestunud.',
  'DeleteOrderCompletelyBoxTip': 'Tellimus kustutatakse täielikult.',
};
Localization.OrderOrder = {
  'PackageBoxTipText': 'Veendu, et pakett „{0}“ sisaldab Sind huvitavaid teoseid, <a href="{1}" class="system-link" target="_blank">tutvu paketi teostega siin</a>.',
  'ErrorMandatoryPackage': 'Pakett peab olema valitud.',
  'ConfirmationNeededBoxTipMessageSingle': 'Tellimus läheb peale kinnitamist ülevaatusele, kuna valisid paketi {0}. Opiq kinnitab tellimuse pärast soodustuse kehtivuses veendumist.',
  'ErrorMustAgreeToTermsAndConditions': 'Tutvu ja nõustu tellimistingimustega.',
  'ErrorPaymentMethodNotSelected': 'Maksemeetod peab olema valitud.',
  'ErrorMandatoryCountry': 'Riik peab olema valitud.',
  'ErrorChoosePackage': 'Vali esmalt pakett!',
  'SingleMonth': 'kuu',
  'ErrorMandatoryRegisterCode': 'Registrikood on kohustuslik.',
  'DeleteOrderConfimationDialog': 'Kas oled kindel, et soovid seda teha?',
  'ErrorPackageNotAvailable': 'Antud paketti ei saa enam tellida.',
  'ErrorValidFromMustBeGreaterThanValidUntil': 'Algus peab olema varasem lõpust.',
  'PackageNameInQuotes': '„{0}“',
  'ErrorMandatoryTown': 'Linn või asula on kohustuslik.',
  'ConfimationDialogDeleteLicenseRow': 'Kas oled kindel, et soovid seda teha?',
  'ConfirmationNeededBoxTipMessageMultiple': 'Tellimus läheb peale kinnitamist ülevaatusele, kuna valisid paketid {0}. Opiq kinnitab tellimuse pärast soodustuse kehtivuses veendumist.',
  'SchoolConfirmationModalTextWithConfirmationNeededPackage': 'Kinnitad tellimuse summas {0}, mis läheb Opiqusse ülevaatusele. Opiq kinnitab tellimuse pärast soodustuse kehtivuses veendumist. Tellimuse ülevaatus võib võtta aega. Tellimuse kinnituse saavad oma e-posti aadressile kõik selle kooli kooliadministraatorid.',
  'ErrorMandatoryInvoiceRecipientName': 'Sisesta arve saaja nimi.',
  'PrivateUserConfirmationModalText': 'Enne tellimuse kinnitamist veendu, et valitud pakett sisaldaks soovitud teoseid ja kehtivuse algus ning pikkus oleksid õiged.',
  'ProductSummarySingleMonth': 'Opiqu kasutuslitsents „{0}” kehtivusega 1 kuu ({1}–{2}) hinnaga {3}.',
  'MultipleMonths': 'kuud',
  'Day': 'päev',
  'ErrorPaymentScheduleNotCalculated': 'Maksegraafik peab olema arvutatud.',
  'ErrorMandatoryLicenseValidUntil': 'Lõpp peab olema valitud.',
  'SingleYear': 'aasta',
  'ErrorMandatoryLicenseValidFrom': 'Algus peab olema valitud.',
  'ProductSummaryMultipleMonths': 'Opiqu kasutuslitsents „{0}” kehtivusega {1} kuud ({2}–{3}) hinnaga {4}.',
  'SchoolConfirmationModalText': 'Kinnitad tellimuse summas {0}, mis tuleb tasuda vastavalt valitud maksetingimustele. Tellimuse kinnituse saavad oma e-posti aadressile kõik selle kooli kooliadministraatorid.',
  'OverlappingPendingLicensesWarning': 'Paketi „{0}“ kehtivus {1}–{2} kattub paketi „{3}“ kehtivusega {4}–{5}!',
  'ErrorMandatoryCounty': 'Maakond on kohustuslik.',
  'MultipleYears': 'aastat',
  'ErrorMandatoryStreetAndHouse': 'Tänavanimi ja majanumber on kohustuslikud.',
  'ErrorInvalidEmail': 'Kontrolli e-posti aadressi. Lubatud on ladina tähestiku sümbolid.',
  'ErrorAtLeastOneLicenseMandatory': 'Tellimuses peab olema vähemalt üks rida!',
  'DeleteOrderBoxTip': 'Tellimus kustutatakse.',
  'ErrorMandatoryZipCode': 'Postiindeks on kohustuslik.',
  'ErrorQuantityBiggerThanOne': 'Kogus peab olema nullist suurem.',
  'ErrorMandatoryEmailAddress': 'Sisesta e-posti aadress.',
};
Localization.PageHeaderComponent = {
  'GenericLicensesTitle': 'Litsentsid',
  'GenericFailedImportsTitle': 'Ebaõnnestunud avaldamised',
  'GenericRegistersTitle': 'Päevikud',
  'GenericStudyProgressTitle': 'Õppejärg',
  'GenericSuccessfulImportsTitle': 'Õnnestunud avaldamised',
  'HeaderTitleExerciseNotSavedMessage': 'salvestamata',
  'GenericInProgressImportsTitle': 'Avaldamisel teosed',
  'HeaderTitleExerciseSavedMessage': 'salvestatud',
  'GenericOrdersTitle': 'Tellimused',
  'GenericTasksTitle': 'Tööd',
};
Localization.PrivateUserKitIndex = {
  'TOCSetCurrentChapter': 'Määra järjehoidjaks',
  'TOCCurrentChapterTooltip': 'See peatükk on määratud järjehoidjaks',
  'RemoveSuccessMessage': 'Teos on õppematerjali hulgast eemaldatud.',
};
Localization.RegisterAdminAddRegister = {
  'RegisterErrorMandatoryKit': 'Õppekomplekt on kohustuslik.',
  'SubmitButtonTextSaveAndSendInvitation': 'Salvesta ja saada kutsed',
  'RegisterErrorMandatoryRegisterName': 'Päeviku nimi on kohustuslik.',
};
Localization.RegisterAdminModifyName = {
  'ValidationErrorNotSuccessfulNameModification': 'Päeviku nime muutmine ebaõnnestus.',
};
Localization.RegisterAdminUpdateKit = {
  'DropdownPlaceholderText': 'Vali',
};
Localization.RegisterKitSettings = {
  'StudentsPackageRemovedSuccessfully': 'Litsentsi lisamine on peatatud!',
  'ConfirmationModalBody': 'Kas oled kindel, et soovid seda teha?',
  'ConfirmationModalBoxTip': 'Koodiga liitumine peatatakse. Liitumise uuesti aktiveerimisel genereeritakse uus kood, senist koodi enam kasutada ei saa.',
  'NotifyCodeWasCopied': 'Kood kopeeriti',
};
Localization.RegisterKitTaskResults = {
  'SelectListTextAll': 'Kõik',
  'TaskTypesSelectionLabelAllTypes': 'Kõik tüübid',
  'NotifyErrorPeriodHasBeenLimitedToOneYear': 'Periood ei tohi olla pikem kui üks aasta.',
  'AppliedTaskTypesCountMessage': '{0} valitud',
};
Localization.RegisterLicensing = {
  'ConfirmationModelConfirmText': 'Kas oled kindel, et soovid õpilastele litsentsid lisada?',
  'MissingPackagesToShareError': 'Koolil puuduvad sobivad litsentsid.',
};
Localization.RegisterListSchoolAdmin = {
  'SearchButtonSearchingTitle': 'Otsin…',
  'UserAutoCompletePrompt': 'Sisesta kasutaja perenimi',
  'SearchButtonDefaultTitle': 'Otsi',
};
Localization.SchoolSettingsConfirmation = {
  'GenericBindingConfirmationDialog': 'Kas Sa oled kindel?',
  'ConfirmationDialogAstraSchoolSameAsStuudiumSchool': 'Kas Sa oled kindel, et Opiqu kool {0} ja Stuudiumi kool {1} on üks ja seesama kool?',
};
Localization.SchoolStudySeasonActivateNextComing = {
  'ConfimationDialogActivateNextComingStudySeason': 'Kas oled kindel, et soovid alustada uut õppeaastat? Käesolev õppeaasta suletakse ja kõik õppegrupid ning päevikud kantakse arhiivi.',
};
Localization.Search = {
  'ExercisesSearchTooltipTextUserLacksRegisters': 'Töö koostamiseks peab Sul olema vähemalt üks päevik.',
};
Localization.SolvingExercise = {
  'HeaderTitleExerciseNotSavedMessage': 'salvestamata',
  'HeaderTitleExerciseSavedMessage': 'salvestatud',
};
Localization.StudentResultsIndex = {
  'ShowClassAverageButton': 'Näita klassi keskmist',
  'ScoreResultsTooltip': 'Siin näidatakse ainult neid töid, mille tulemuseks on sooritusprotsent.',
  'HideClassAverageButton': 'Peida klassi keskmine',
  'GradeResultsTooltip': 'Siin näidatakse ülevaadet ainult numbriliselt hinnatud töödest.',
};
Localization.StudentResultsSingleSubject = {
  'NotifyErrorPeriodEndBeforePeriodStart': 'Perioodi lõpp ei saa olla varem kui perioodi algus.',
  'NotifyErrorPeriodLengthLimitation': 'Periood ei tohi olla pikem kui üks aasta.',
};
Localization.StudyGroupAdd = {
  'ErrorMandatoryClassNumber': 'Klassinumber on kohustuslik.',
  'ErrorNegativeNumber': 'Klassinumber peab olema mittenegatiivne täisarv.',
};
Localization.StudyGroupModifyName = {
  'ErrorMandatoryClassNumber': 'Klassinumber on kohustuslik.',
  'ErrorNegativeNumber': 'Klassinumber peab olema mittenegatiivne täisarv.',
};
Localization.TaskAdd = {
  'NotifySuccessDraftSaved': 'Töö on salvestatud.',
  'TextReadThroughTheChapter': 'Loe peatükk „{0}” läbi.',
  'NotifyErrorTooManyExercisesSelected': 'Ühes töös tohib olla kuni {0} ülesannet.',
  'NotifySuccessTaskAssigned': 'Töö on määratud!',
  'NotifyErrorMandatoryExercise': 'Vähemalt üks ülesanne peab olema valitud!',
  'NotifyErrorMandatoryRegister': 'Päevik peab olema valitud!',
  'NotifyErrorMandatoryTitle': 'Pealkiri peab olema määratud!',
  'NotifyErrorMandatoryAddress': 'Töö saaja peab olema valitud!',
  'NotifyErrorMandatoryDeadline': 'Tähtaeg peab olema määratud!',
  'ConfimationDialogDeleteDraftTask': 'Kas oled kindel, et soovid töö mustandi kustutada?',
  'NotifySuccessTaskDeleted': 'Töö mustand kustutatud!',
};
Localization.TaskAddExercises = {
  'SelectListPlaceholderText': 'Vali',
  'NotifyExercisesAddedSuccessMessage': 'Ülesanded lisati tööle',
};
Localization.TaskEvaluationIndex = {
  'StatusRejected': 'Tagasi saadetud',
  'SaveAndDiscloseButtonScore': 'Avalda sooritusprotsent',
  'SaveAndDiscloseButtonGrade': 'Avalda hinne',
  'TaskRejectedSuccessMessage': 'Töö on õpilasele tagasi saadetud!',
  'SaveAndDiscloseButtonOtherGrade': 'Avalda muu hinne',
  'SaveAndDiscloseButtonFormativeGrade': 'Avalda kujundav hindamine',
  'StatusNotGraded': 'Hindamata',
  'StudentMessageHeading': 'Õpilase teade:',
  'ButtonTextShowMore': 'Rohkem andmeid',
  'ButtonTextShowLess': 'Vähem andmeid',
  'ScoreNotDisclosableText': 'Sooritusprotsent ei ole arvutatav.',
  'StatusNotDisclosed': 'Avaldamata',
  'DiscloseScoreInfo': 'Avalda tulemusena õpilase töö sooritusprotsent.',
  'StatusDisclosed': 'Avaldatud',
  'SomeAnswersUncheckedToolTipFormat': '{0} vastust on kontrollimata',
  'ValidationMaterialBlockHeadingTeacherRecentAddedMaterial': 'Õpetaja viimati lisatud materjal',
};
Localization.TaskReviewIndex = {
  'ButtonTextDiscloseSelected': 'Avalda valitud ({0})',
  'ReclaimedAssignedTaskHeading': 'Õpilane küsis töö tagasi',
  'ConfimationDialogDeleteStudentTask': 'Kas oled kindel, et soovid õpilase töö kustutada? Kui õpilane on juba tööd lahendanud ja vastuseid salvestanud, siis need vastused kustutatakse.',
  'LinkCopiedSuccessText': 'Link kopeeriti',
  'OnlySubmittedTasksCanBeRejectedErrorMessage': 'Tagasi saab saata esitatud töid!',
  'ConfimationDialogDeleteTask': 'Kas oled kindel, et soovid töö kustutada? Kui õpilased on juba tööd lahendanud ja vastuseid salvestanud, siis need vastused kustutatakse.',
  'TaskWillBeDeletedFromeKoolTip': 'eKoolis tööd ei kustutata.',
  'DiscloseWarningMessageForMultipleReclaimedTasks': '{0} õpilast küsisid töö tagasi.',
  'DiscloseWarningConfirmationForOneReclaimedTask': 'Kas oled kindel, et soovid töö avaldada?',
  'DisclosedTasksCanNotBeDisclosedErrorMessage': 'Juba avaldatud töid ei ole vaja uuesti avaldada!',
  'TasksRejectedSuccessMessage': 'Tööd on õpilastele tagasi saadetud!',
  'TaskWillBeDeletedFromstuudiumTip': 'Töö kustutatakse ka Stuudiumist.',
  'DiscloseWarningConfirmationForMultipleReclaimedTasks': 'Kas oled kindel, et soovid tööd avaldada?',
  'ButtonTextRejectSelected': 'Saada tagasi ({0})',
  'DiscloseWarningMessageForOneReclaimedTask': 'Õpilane küsis töö tagasi.',
};
Localization.TaskSolvingIndex = {
  'ExerciseAnswerNotSaved': 'Selle ülesande vastus ei ole salvestatud.',
  'AnswerIsTooLong': 'Vastus on liiga pikk!',
  'ConfirmationDialogSubmitTask': 'Kas oled kindel, et soovid töö esitada?',
  'ChapterNotMarkedRead': 'Peatükk ei ole märgitud läbitöötatuks.',
};
Localization.TaskStatistics = {
  'Tooltip': '{0}<br/>{1}/{2} ehk {3}% töödest',
};
Localization.TeacherDesktopTasks = {
  'Deadline': 'Tähtaeg',
  'ConfirmationDialogRemoveFromDesktop': 'Kas Sa oled kindel, et soovid töö esilehelt eemaldada? Töö on endiselt leitav päeviku tööde küljelt.',
  'Submitted': 'Esitatud',
};
Localization.UserDetails = {
  'RemoveLicenseConfirmation': 'Kas Sa soovid kasutajalt litsentsi eemaldada?',
  'InvitationSentMessage': 'Kutse on saadetud!',
};
Localization.UserMaterial = {
  'NoTextEnteredErrorMessage': 'Palun sisestage tekst.',
  'AddTextHeading': 'Lisa tekst',
  'DeleteTextConfirmationMessage': 'Kas kustutada tekst?',
  'FileUploadFailedErrorMessage': 'Faili salvestamine ebaõnnestus.',
  'DeleteImageConfirmationMessage': 'Kas kustutada pilt?',
  'AddMaterialHeading': 'Lisa materjali',
  'DeleteFileConfirmationMessage': 'Kas kustutada fail?',
  'SelectFilePrompt': 'Palun valige fail.',
  'AddFileHeading': 'Lisa fail',
  'FilesTooLargeErrorMessage': 'Failid {0} on liiga suured ja neid ei ole võimalik lisada.',
  'ImgDimensionsTooLargeErrorMessage': 'Pildi {0} dimensioonid on liiga suured. Lubatud suurim küljepikkus on {1} pikslit.',
  'UnsupportedFileTypesErrorMessage': 'Selle laiendiga {0} faile ei saa lisada. Faili tüüp ei ole toetatud.',
};
Localization.UsersBatchImport = {
  'HeadingAddedUsers': 'Kasutajaid lisatud {0}/{1}',
};
Localization.UsersRemove = {
  'RemoveSelectedRolesSingleUser': 'Eemalda kasutajalt valitud rollid',
  'DisabledButtonTooltip': 'Rolli eemaldamiseks tuleb kõigepealt valida kasutajad ja roll, mida eemaldada.',
  'RemoveRoleDefaultText': 'Eemalda kasutajatelt roll',
  'RemoveAllRolesMultipleUsers': 'Eemalda {0} kasutajalt kõik rollid',
  'RemoveSpecificRoleMultipleUsers': 'Eemalda {0} kasutajalt roll „{1}”',
  'RemoveAllRolesSingleUser': 'Eemalda kasutajalt kõik rollid',
  'RemoveSelectedRolesMultipleUsers': 'Eemalda {0} kasutajalt valitud rollid',
  'FromMultipleUsers': '{0} kasutajalt',
  'FromSingleUser': '1 kasutajalt',
  'RemoveSpecificRoleSingleUser': 'Eemalda kasutajalt roll „{0}”',
};
