/* This file is auto-generated by a tool */
if (!String.prototype.format) {
  String.prototype.format = function() {
    var args = arguments;
    return this.replace(/{(\d+)}/g, function(match, number) {
      return typeof args[number] != 'undefined'
        ? args[number]
        : match
      ;
    });
  };
}
var Localization = Localization || {};
Localization.AddUsers = {
  'NotifyErrorInvitationCanBeResentOnlyToUsersWithEmails': 'Электронды поштасы жоқ пайдаланушыға шақырту жіберу мүмкін емес.',
  'UserHasEKoolAndStuudiumBinding': 'У пользователя есть привязки к eKool и Stuudium',
  'NotifyErrorChooseMembersToRemove': 'Жойғыңыз келетін пайдаланушыларды белгілеңіз!',
  'NotifyErrorInvitationWasResentOnlyToUsersWithEmails': 'Шақырту тек пайдаланушының электронды поштасына ғана жіберіледі.',
  'NotifyWarningNoUsersAdded': 'Пайдаланушылар қосылмаған!',
  'UserHasStuudiumBinding': 'У пользователя есть привязка к Stuudium',
  'ValidationErrorWrongEmail': 'Электронды поштаның мекенжайын тексеріңіз. Тек латын әріптеріне рұқсат етілген.',
  'NotifyErrorChooseMembersToResendInvitation': 'Қайтадан шақырту жібергіңіз келетін пайдаланушыларды белгілеңіз!',
  'UserHasEKoolBinding': 'У пользователя есть привязка к eKool',
  'ErrorChooseStudents': 'Оқушыларды таңдаңыз!',
  'ValidationErrorFormMustHaveFilledRows': 'Барлық жолдар толтырылуы керек!',
};
Localization.AdminCustomerUsers = {
  'ModalTitle': 'Пайдаланушының ролі жойылады „{0}“.',
};
Localization.AdminUsersSearch = {
  'EnterSchoolNameMessage': 'Мектеп атауын енгізіңіз',
  'LicensePackageAll': 'Барлық пакеттер',
};
Localization.Annotation = {
  'ErrorMessageAnnotationAlreadyDeleted': 'Аңдатпаны өзгерту мүмкін емес, себебі ол жойылған.',
};
Localization.AutoComplete = {
  'SearchingMessage': 'Іздеу…',
  'ErrorLoadingResultsMessage': 'Нәтижелерді жүктеу сәтсіз аяқталды',
  'NoResultsMessage': 'Нәтижелер табылмады',
};
Localization.ChapterExerciseCreate = {
  'NotifyErrorMandatoryChapter': 'Параграфты көрсету керек!',
  'NotifyErrorMandatoryTitle': 'Тақырып міндетті түрде!',
  'NotifyErrorMandatoryKit': 'Оқу жиынтығын көрсету керек!',
};
Localization.ChapterExercisesIndex = {
  'TooltipTextUserNotInActiveRegisters': 'Жұмысты құру үшін сізде соған кем дегенде бір журнал басталған болуы тиіс.',
  'ConfimationDialogAreYouSure': 'Осы әрекетті орындағыңыз келетініне сенімдісіз бе?',
};
Localization.ChapterIndex = {
  'LinkCopiedSuccessMessage': 'Сілтеме көшірілді.',
};
Localization.CouponBatchDetails = {
  'DeleteCouponModalMessage': 'Сыйлық картасы жойылады. Егер клиент сыйлық картасын алып қойған болса, онда ол жойылған соң, оны пайдалануға болмайды.',
};
Localization.CouponCreate = {
  'EnterCustomerNameMessage': 'Клиенттің атын енгізіңіз',
  'PricePerMonthFormat': '{0} ай',
  'CustomerTypeSchool': 'Мектеп',
  'WarningCouponCountBigFormat': '{0} сыйлық карталарын жасағыңыз келетініне сенімдісіз бе?',
  'QuantityMustBeSetError': 'Санын енгізіңіз.',
  'NoResultsMessage': 'Нәтижелер табылған жоқ',
  'CouponCountMustBeSetError': 'Сыйлық карталарының санын енгізіңіз.',
  'PackageMustBeSelectedError': 'Пакетті таңдаңыз.',
  'CouponValidUntilMustBeSetError': 'Сыйлық карталарының аяқталу мерзімін таңдаңыз.',
  'CustomerTypeMustBeSelectedError': 'Клиенттің түрін таңдап алыңыз.',
  'SelectCustomerTypeError': 'Алдымен клиенттің түрін таңдап алыңыз.',
  'CustomerTypePrivateUser': 'Жеке клиент',
  'LengthOfValidityMustBeSetError': 'Жарамдылық мерзімін енгізіңіз.',
};
Localization.CreateCustomer = {
  'NoCustomerTypeSelectedError': 'Клиент түрін таңдаңыз.',
};
Localization.CreateSchoolAdminAccount = {
  'PasswordRepeatDifferentError': 'Құпиясөз және қайта енгізілген құпиясөз сәйкес келмейді.',
  'RequiredFieldLeftEmptyErrorWithArgs': '{0} жолы толтырылуы керек.',
  'Field': 'Жол',
  'PasswordTooShortErrorWithArgs': 'Құпиясөзде кемінде {0} таңба болуы керек.',
  'UserNameInvalidEmailWithArgs': '{0} дұрыс электронды мекенжайды көрсетіңіз.',
};
Localization.Currency = {
  'CurrencyFormatDefault': '{0} {1}',
};
Localization.EditTextExercise = {
  'NeededSpaceRemoval': 'Бірге жазылмағандар',
  'PerformedRemoval': '{0} жойылғандар {1}',
  'NeededSpaceAddition': 'Бөлек жазылмағандар',
  'PerformedSpaceRemoval': 'бірге жазылу {0}',
  'NeededRemoval': 'Жойылмағандар {0}',
  'ExpectedClause': '; {0} болу керек',
  'NeededReplacement': 'Түзетілмегендер <i>{0} → {1}</i>',
  'EvaluationCorrectly': 'Дұрыс',
  'PerformedSpaceAddition': 'бөлек жазылу {0}',
  'EvaluationIncorrectly': 'Қате',
  'NeededAddition': 'Қосылмағандар {0}',
  'PerformedAddition': '{0} қосылғандар {1}',
  'PerformedReplacement': '{0} түзетілгендер <i>{1} → {2}</i>',
};
Localization.ErrorReportModal = {
  'ErrorReportContactInfoExcessiveLength': 'Байланыс деректері  {0} символдан тұруы мүмкін, сіз {1} енгіздіңіз.',
  'AddErrorDescription': 'Қатені сипаттаңыз!',
  'ErrorReportDescriptionExcessiveLength': 'Қатенің сипаттамасы  {0} символға дейін болуы мүмкін, сіз  {1} енгіздіңіз.',
  'ErrorReportCreated': 'Хабарлама сақталды',
};
Localization.ExerciseMenu = {
  'ExerciseToolTipText': 'Жұмыстың тапсырмасы',
  'ChapterExerciseToolTipText': 'Параграфтың тапсырмасы',
};
Localization.Exercises = {
  'DragFromGroupTitle': 'Жауапты қажетті бағанға сүйреп апарыңыз',
  'ChangeButtonText': 'Өзгерту',
  'DragHerePlaceholder': 'осында сүйреп әкеліңіз',
  'SaveButtonText': 'Сақтау',
  'TeachersCommentHeading': 'Мұғалімнің түсініктемесі {0}',
  'CheckAnswerButtonText': 'Жауапты тексеру',
  'NoAnswerSelectedByStudent': 'Жауап таңдалмады',
  'ButtonTextShowMyAnswers': 'Менің жауаптарымды көрсету',
  'MethodologicalTextSectionHeading': 'NB! Оқушыларға бұл элемент көрінбейді.',
  'ButtonTextShowStudentsAnswers': 'Оқушылардың жауаптарын көрсету',
  'FixMistakesButtonText': 'Жауапты өзгерту',
  'ExerciseOldCommentWarning': 'Бұл мұғалімнің ескі түсініктемесі ({0}). Сіз осы түсініктемені қайтадан жібергіңіз келетініне сенімдісіз бе?',
  'HideExampleAnswersText': 'Жауаптың үлгісін көрсетпеу',
  'TryAgainButtonText': 'Басынан бастау',
  'NoAnswerSelectedByYou': 'Жауаптарды таңдалмаған күйде қалдыру',
};
Localization.FoxGraph = {
  'ButtonTextLoad': 'Жүктеу',
};
Localization.Global = {
  'SavedNotificationMessage': 'Сақталды',
  'LoadingContentMessage': 'Жүктелуде…',
  'AjaxErrorSessionExpired': 'Сессия аяқталды!',
  'AjaxErrorNoAccess': 'Бұл ресурс пайдаланушыға қолжетімді емес!',
  'AjaxErrorSessionChanged': 'Пайдаланушы сеансы сәтсіз аяқталды, бетті жаңартыңыз!',
  'AjaxErrorNoConnection': 'Сервермен байланыс жоқ!',
  'DatepickerLanguageCode': 'kk',
  'ConfirmationModalQuestion': 'Сіз мұны жасағыңыз келетініне сенімдісіз бе?',
  'AjaxErrorConcurrency': 'Деректер жаңартылды, бетті жаңартуыңызды сұраймыз!',
  'AjaxErrorOther': 'Бірдеңе дұрыс емес :(',
};
Localization.InvoiceRecipient = {
  'ConfirmClearInvoiceRecipientText': 'Сіз шынымен шотты алушының деректерін жойғыңыз келе ме?',
};
Localization.JoinRegister = {
  'SuccessfullyJoinedRegister': 'Сіз журналға қосылдыңыз!',
};
Localization.JoinSchool = {
  'SuccessfullyJoinedSchool': 'Мектепке қосылдыңыз!',
};
Localization.KitAddKitToRegisters = {
  'ChooseRegistersPlaceholder': 'Таңдау',
  'NotifySuccessMessageAddedToSingleRegister': 'Оқу жиынтығы журналға қосылды',
  'NotifySuccessMessageAddedToMultipleRegisters': 'Оқу жиынтығы журналдарға қосылған',
};
Localization.KitCreateRegisterFromKit = {
  'NotifyErrorMessageDataNotSaved': 'Деректерді сақтау сәтсіз аяқталды!',
  'ErrorMessageTeacherNotFound': 'Мұғалім табылмады, мұғалімді тізімнен таңдаңыз!',
  'NotifySuccessMessageDataSaved': 'Деректер сақталды!',
};
Localization.KitDetails = {
  'InUseSingleRegister': '1 журналда қолданылады',
  'InUseRegisters': '{0} журналдарда қолданылады',
  'RemoveSuccessMessage': 'Шығарма оқу жиынтықтарының тізімінен алынып тасталды.',
};
Localization.LicensingIndex = {
  'LicenseButtonLicenseNUsersText': '{0} пайдаланушыны лицензиямен  қамтамасыз ету',
  'LicenseButtonLicenseOneUserText': '1 пайдаланушыны лицензиямен қамтамасыз ету',
  'LicenseButtonText': 'Лицензиямен қамтамасыз ету',
  'LicenseSelectionPlaceHolder': 'Лицензияны таңдаңыз',
};
Localization.LicensingRemoveLicenses = {
  'ButtonRemoveLicenseNUsersText': '{0} пайдаланушының лицензиясын жою',
  'LicenseMissing': 'лицензия жоқ',
  'RemoveLicenseButtonText': 'Жою',
  'ButtonTooltipNoLicenseSelected': 'Жою үшін пайдаланушыда бұрыннан бар лицензияны таңдаңыз',
  'ChosenLicenseMissing': 'таңдалған лицензия жоқ',
  'ButtonTooltipNoUsersSelected': 'Алдымен пайдаланушыларды таңдап алып, содан кейін олардың лицензияларын жойыңыз',
  'LicenseSelectionPlaceHolder': 'Лицензияны таңдаңыз',
};
Localization.ManageIndex = {
  'ConfirmationDialog': 'Бұл әрекетті орындағыңыз келтіндігіне сенімдісіз бе?',
};
Localization.ManageLinkLoginConfirmation = {
  'ConfirmationDialog': 'Бұл әрекетті орындағыңыз келтіндігіне сенімдісіз бе?',
};
Localization.MediaGallery = {
  'ExitFullscreen': 'Толық экранды режимнен шығу',
  'SendToProjector': 'Проекторға беру',
  'ShowFullscreen': 'Толық экранды режимді қосу',
};
Localization.OrderDetails = {
  'ConfirmationModalMessage': 'Осы әрекетті орындағыңыз келетініне сенімдісіз бе?',
  'ReturnToDraftModalBoxTip': 'Заказ открывается, школа может изменить заказ и снова его подтвердить.',
  'OrderWillBeConfirmedBoxTip': 'Заказ подтверждается.',
  'ActionFailedMessage': 'Действие не удалось.',
  'DeleteOrderCompletelyBoxTip': 'Заказ удаляется полностью.',
};
Localization.OrderOrder = {
  'PackageBoxTipText': '«{0}» пакет сізді қызықтырып отырған басылымдарынан тұратындығына көз жеткізіңіз <a href="{1}" class="system-link" target="_blank">пакетіне кіретін басылымдармен танысу</a>.',
  'ErrorMandatoryPackage': 'Пакет таңдалуы керек.',
  'ConfirmationNeededBoxTipMessageSingle': 'Тапсырыс расталған соң тексерістен өтеді, себебі сіз  {0} пакетті таңдап алдыңыз.  Opiq жеңілдіктің болып жатқандығына көз жеткізген соң тапсырысты бекітеді.',
  'ErrorMustAgreeToTermsAndConditions': 'Тапсырыс шарттарымен танысыңыз және өз келісіміңізді растаңыз.',
  'ErrorPaymentMethodNotSelected': 'Төлем әдісін таңдаңыз.',
  'ErrorMandatoryCountry': 'Елді таңдап алу керек.',
  'ErrorChoosePackage': 'Алдымен пакетті таңдаңыз!',
  'SingleMonth': 'ай',
  'ErrorMandatoryRegisterCode': 'Тіркеу коды міндетті түрде болу керек.',
  'DeleteOrderConfimationDialog': 'Сіз осыны жасағыңыз келетініне сенімдісіз бе?',
  'ErrorPackageNotAvailable': 'Осы пакетке енді тапсырыс беруге болмайды.',
  'ErrorValidFromMustBeGreaterThanValidUntil': 'Мерзімнің аяқталу күні оның басталу күнінен ерте болмауы керек.',
  'PackageNameInQuotes': '«{0}»',
  'ErrorMandatoryTown': 'Қала немесе елді мекенді көрсету керек.',
  'ConfimationDialogDeleteLicenseRow': 'Сіз осыны жасағыңыз келетініне сенімдісіз бе?',
  'ConfirmationNeededBoxTipMessageMultiple': 'Тапсырыс расталған соң тексерістен өтеді, себебі сіз {0} пакетін таңдап алғансыз. Opiq жеңілдіктің болып жатқандығына көз жеткізген соң тапсырысты бекітеді.',
  'SchoolConfirmationModalTextWithConfirmationNeededPackage': 'Сіз {0} сомасындағы тапсырысты растайсыз, ол  Opiq-ке тексеруге жіберіледі. Opiq жеңілдік болып жатқандығына көз жеткізілген соң, тапсырысты бекітеді. Тапсырысты тексеру біраз уақытты алуы мүмкін.',
  'ErrorMandatoryInvoiceRecipientName': 'Алушының атын енгізіңіз.',
  'PrivateUserConfirmationModalText': 'Тапсырысты растамас бұрын таңдалған пакет сізді қызықтырып отырған басылымдардан тұратындығына көз жеткізіңіз, сонымен қатар, әрекет етудің басталуы мен мерзімі сізге сәйкес келеді.',
  'ProductSummarySingleMonth': 'Opiq қолдануға лицензия «{0}» 1 айлық мерзімге ({1}–{2}) құны {3}.',
  'MultipleMonths': 'айлар',
  'Day': 'күн',
  'ErrorPaymentScheduleNotCalculated': 'Төлем кестесін есептеңіз.',
  'ErrorMandatoryLicenseValidUntil': 'Кезеңнің соңы таңдалуы керек.',
  'SingleYear': 'жыл',
  'ErrorMandatoryLicenseValidFrom': 'Басталу кезеңі таңдалуы тиіс.',
  'ProductSummaryMultipleMonths': 'Opiq қолдануға лицензия «{0}» кезеңге {1} ай ({2}–{3}) құны {4} .',
  'SchoolConfirmationModalText': '{0} сомасындағы тапсырысты растаңыз, оны таңдап алынған төлеу талаптарына сәйкес төлеу керек. Тапсырыстың растамасы осы мектептің бүкіл әкімшілерінің электронды пошатсына жіберіледі.',
  'OverlappingPendingLicensesWarning': '„{0}“ ({1}–{2}) пакетінің қолданылу мерзімі „{3}“ ({4}–{5}) пакетінің қолданылу мерзімімен қиылысады!',
  'ErrorMandatoryCounty': 'Уезді көрсету керек.',
  'MultipleYears': 'жыл',
  'ErrorMandatoryStreetAndHouse': 'Көшенің аты мен үйдің номерін көрсету керек.',
  'ErrorInvalidEmail': 'Электронды поштаңыздың мекенжайын тексеріңіз. Тек латын әріптеріне рұқсат етілген.',
  'ErrorAtLeastOneLicenseMandatory': 'Тапсырыста кем дегенде бір жол толтырылуы тиіс!',
  'DeleteOrderBoxTip': 'Тапсырыс алынып тасталады.',
  'ErrorMandatoryZipCode': 'Пошта индексін көрсету керек.',
  'ErrorQuantityBiggerThanOne': 'Саны нөлден жоғары болуы керек.',
  'ErrorMandatoryEmailAddress': 'Электронды мекенжайды енгізіңіз.',
};
Localization.PageHeaderComponent = {
  'GenericLicensesTitle': 'Лицензиялар',
  'GenericFailedImportsTitle': 'Сәтсіз жарияланымдар',
  'GenericRegistersTitle': 'Журналдар',
  'GenericStudyProgressTitle': 'Ағымдағы параграф',
  'GenericSuccessfulImportsTitle': 'Сәтті жарияланымдар',
  'HeaderTitleExerciseNotSavedMessage': 'сақталған жоқ',
  'GenericInProgressImportsTitle': 'Жарияланған басылымдар',
  'HeaderTitleExerciseSavedMessage': 'сақталған',
  'GenericOrdersTitle': 'Тапсырыстар',
  'GenericTasksTitle': 'Жұмыстар',
};
Localization.PrivateUserKitIndex = {
  'TOCSetCurrentChapter': 'Ағымдағы тақырыпты беру',
  'TOCCurrentChapterTooltip': 'Бұл параграф бетбелгімен белгіленген',
  'RemoveSuccessMessage': 'Басылым оқу материалдарының тізімінен алынып тасталды.',
};
Localization.RegisterAdminAddRegister = {
  'RegisterErrorMandatoryKit': 'Оқу жиынтығы көрсетілуі керек.',
  'SubmitButtonTextSaveAndSendInvitation': 'Шақыртуды сақтау және жіберу',
  'RegisterErrorMandatoryRegisterName': 'Журналдың аты міндетті түрде.',
};
Localization.RegisterAdminModifyName = {
  'ValidationErrorNotSuccessfulNameModification': 'Журналдың атауын өзгерту сәтсіз аяқталды.',
};
Localization.RegisterAdminUpdateKit = {
  'DropdownPlaceholderText': 'Таңдау',
};
Localization.RegisterKitSettings = {
  'StudentsPackageRemovedSuccessfully': 'Лицензияны қосу тоқтатылды!',
  'ConfirmationModalBody': 'Бұл әрекетті орындағыңыз келтіндігіне сенімдісіз бе?',
  'ConfirmationModalBoxTip': 'Кодтың көмегімен қосылу  тоқтатыла тұрады. Қайта белсендендірген кезде жаңа код генерирленеді, қолданыстағы код енді қолданылмайды.',
  'NotifyCodeWasCopied': 'Кодты көшіру',
};
Localization.RegisterKitTaskResults = {
  'SelectListTextAll': 'Барлығы',
  'TaskTypesSelectionLabelAllTypes': 'Барлық түрлері',
  'NotifyErrorPeriodHasBeenLimitedToOneYear': 'Мерзім бір жылдан аспауы тиіс.',
  'AppliedTaskTypesCountMessage': '{0} таңдалды',
};
Localization.RegisterLicensing = {
  'ConfirmationModelConfirmText': 'Сіз оқушыларға лицензия қосқыңыз келетініне сенімдісіз бе?',
  'MissingPackagesToShareError': 'Мектепте тиісті лицензиялар жоқ.',
};
Localization.RegisterListSchoolAdmin = {
  'SearchButtonSearchingTitle': 'Іздеуде …',
  'UserAutoCompletePrompt': 'Пайдаланушының тегін енгізіңіз',
  'SearchButtonDefaultTitle': 'Іздеу',
};
Localization.SchoolSettingsConfirmation = {
  'GenericBindingConfirmationDialog': 'Сіз сенімдісіз бе?',
  'ConfirmationDialogAstraSchoolSameAsStuudiumSchool': 'Opiq {0} және Stuudium {1}-де бір мектеп көрсетілгеніне сенімдісіз бе?',
};
Localization.SchoolStudySeasonActivateNextComing = {
  'ConfimationDialogActivateNextComingStudySeason': 'Сіз жаңа оқу жылын бастағыңыз келетініне сенімдісіз бе? Ағымдағы оқу жылы аяқталады да оқушылардың барлық топтары мен журналдар мұрағатқа көшіріледі.',
};
Localization.Search = {
  'ExercisesSearchTooltipTextUserLacksRegisters': 'Тапсырманы құрастыру үшін сізде кем дегенде бір журнал ғана басталған болуы тиіс.',
};
Localization.SolvingExercise = {
  'HeaderTitleExerciseNotSavedMessage': 'сақталған жоқ',
  'HeaderTitleExerciseSavedMessage': 'сақталған',
};
Localization.StudentResultsIndex = {
  'ShowClassAverageButton': 'Орташа сыныпты көрсету',
  'ScoreResultsTooltip': 'Бұл жерде орындалу пайызын ескере отырып бағаланған жұмыстарға шолу ұсынылған.',
  'HideClassAverageButton': 'Орташа сыныпты жасыру',
  'GradeResultsTooltip': 'Бұл жерде баллдармен бағаланған жұмыстарға шолу ұсынылған.',
};
Localization.StudentResultsSingleSubject = {
  'NotifyErrorPeriodEndBeforePeriodStart': 'Кезеңнің аяқталу күні оның басталу күнінен ерте болмауы тиіс.',
  'NotifyErrorPeriodLengthLimitation': 'Мерзім бір жылдан аспауы тиіс.',
};
Localization.StudyGroupAdd = {
  'ErrorMandatoryClassNumber': 'Сынып нөмірі міндетті түрде.',
  'ErrorNegativeNumber': 'Сынып нөмірі теріс сан болуы мүмкін емес.',
};
Localization.StudyGroupModifyName = {
  'ErrorMandatoryClassNumber': 'Сынып нөмірі міндетті түрде.',
  'ErrorNegativeNumber': 'Сынып нөмірі теріс сан болуы мүмкін емес.',
};
Localization.TaskAdd = {
  'NotifySuccessDraftSaved': 'Жұмыс сақталды.',
  'TextReadThroughTheChapter': 'Параграфты «{0}» оқыңыз.',
  'NotifyErrorTooManyExercisesSelected': 'Бір жұмыста {0}-ден артық жұмыс болмауы тиіс.',
  'NotifySuccessTaskAssigned': 'Жұмыс тағайындалды!',
  'NotifyErrorMandatoryExercise': 'Кемінде бір тапсырма таңдалуы керек!',
  'NotifyErrorMandatoryRegister': 'Журналды таңдап алу қажет!',
  'NotifyErrorMandatoryTitle': 'Тақырып міндетті түрде!',
  'NotifyErrorMandatoryAddress': 'Жұмыстарды алушы көрсетілуі керек!',
  'NotifyErrorMandatoryDeadline': 'Орындалу мерзімі көрсетілуі керек!',
  'ConfimationDialogDeleteDraftTask': 'Сіз жұмыстың шимай жазбасын жойғыңыз келетініне сенімдісіз бе?',
  'NotifySuccessTaskDeleted': 'Шимай жазба жойылды!',
};
Localization.TaskAddExercises = {
  'SelectListPlaceholderText': 'Таңдау',
  'NotifyExercisesAddedSuccessMessage': 'Тапсырмалар жұмысқа қосылды',
};
Localization.TaskEvaluationIndex = {
  'StatusRejected': 'Кері жіберілді',
  'SaveAndDiscloseButtonScore': 'Орындалған жұмыс пайызын жариялау',
  'SaveAndDiscloseButtonGrade': 'Бағаларын жариялау',
  'TaskRejectedSuccessMessage': 'Жұмыс оқушыға жіберілді!',
  'SaveAndDiscloseButtonOtherGrade': 'Басқа бағаны жариялаңыз',
  'SaveAndDiscloseButtonFormativeGrade': 'Қалыптастырушы бағалауды жариялау',
  'StatusNotGraded': 'Бағаланбаған',
  'StudentMessageHeading': 'Оқушының хабарламасы:',
  'ButtonTextShowMore': 'Толығырақ',
  'ButtonTextShowLess': 'Деректер аздау',
  'ScoreNotDisclosableText': 'Орындалу пайызын есептеу мүмкін емес.',
  'StatusNotDisclosed': 'Жарияланған жоқ',
  'DiscloseScoreInfo': 'Оқушының орындаған жұмыс пайызын жариялау.',
  'StatusDisclosed': 'Жарияланған',
  'SomeAnswersUncheckedToolTipFormat': '{0} жауап тексерілмеді',
  'ValidationMaterialBlockHeadingTeacherRecentAddedMaterial': 'Мұғалім қосқан соңғы материал',
};
Localization.TaskReviewIndex = {
  'ButtonTextDiscloseSelected': 'Таңдалғанды жариялау ({0})',
  'ReclaimedAssignedTaskHeading': 'Оқушы жұмысын кері сұратты',
  'ConfimationDialogDeleteStudentTask': 'Сіз оқушы жұмысын алып тастағыңыз келетініне сенімдісіз бе? Егер оқушы тапсырманы орындап, жауаптарды сақтап қойған болса, олар жойылады.',
  'LinkCopiedSuccessText': 'Сілтеме көшірілді',
  'OnlySubmittedTasksCanBeRejectedErrorMessage': 'Тек тапсырылған жұмыстарды жіберуге болады!',
  'ConfimationDialogDeleteTask': 'Сіз жұмысты алып тастағыңыз келетініне сенімдісіз бе? Егер оқушылар тапсырманы орындап, жауаптарды сақтап қойған болса, олар жойылады.',
  'TaskWillBeDeletedFromeKoolTip': 'Работы eKool не удаляются.',
  'DiscloseWarningMessageForMultipleReclaimedTasks': '{0} оқушы жұмысын кері сұратты.',
  'DiscloseWarningConfirmationForOneReclaimedTask': 'Сіз жұмысты жариялағыңыз келетініне сенімдісіз бе?',
  'DisclosedTasksCanNotBeDisclosedErrorMessage': 'Жарияланған жұмыстарды қайта жариялау қажет емес!',
  'TasksRejectedSuccessMessage': 'Оқушылардың жұмыстары тексерілді және жіберілді!',
  'TaskWillBeDeletedFromstuudiumTip': 'Жұмыс Stuudium-нан да жойылады.',
  'DiscloseWarningConfirmationForMultipleReclaimedTasks': 'Сіз жұмысты жариялағыңыз келетініне сенімдісіз бе?',
  'ButtonTextRejectSelected': 'Қайта жіберу ({0})',
  'DiscloseWarningMessageForOneReclaimedTask': 'Оқушы жұмысын кері сұратты.',
};
Localization.TaskSolvingIndex = {
  'ExerciseAnswerNotSaved': 'Тапсырманың жауабы сақталған жоқ.',
  'AnswerIsTooLong': 'Тым ұзақ жауап!',
  'ConfirmationDialogSubmitTask': 'Жұмысты көрсеткіңіз келетіндігіне сенімдісіз бе?',
  'ChapterNotMarkedRead': 'Параграф пысықталды деп белгіленіп тұрған жоқ.',
};
Localization.TaskStatistics = {
  'Tooltip': 'Жұмыстардың {0}<br/>{1}/{2} немесе {3}%',
};
Localization.TeacherDesktopTasks = {
  'Deadline': 'Мерзімі',
  'ConfirmationDialogRemoveFromDesktop': 'Жұмысты басты беттен жойғыңыз келетіндігіне сенімдісіз бе? Жұмыс бұрынғысындай журналдың бүйір мәзірінде тұр.',
  'Submitted': 'Ұсынылды',
};
Localization.UserDetails = {
  'RemoveLicenseConfirmation': 'Пайдаланушы лицензиясын жойғыңыз келетіндігіне сенімдісіз бе?',
  'InvitationSentMessage': 'Шақырту жіберілді!',
};
Localization.UserMaterial = {
  'NoTextEnteredErrorMessage': 'Мәтінді енгізіңіз.',
  'AddTextHeading': 'Мәтін қосу',
  'DeleteTextConfirmationMessage': 'Мәтінді жойғыңыз келе ме?',
  'FileUploadFailedErrorMessage': 'Файл сақталмады.',
  'DeleteImageConfirmationMessage': 'Суретті алып тастағыңыз келе ме?',
  'AddMaterialHeading': 'Материал қосу',
  'DeleteFileConfirmationMessage': 'Файлды жойғыңыз келе ме?',
  'SelectFilePrompt': 'Файлды таңдаңыз.',
  'AddFileHeading': 'Файл қосу',
  'FilesTooLargeErrorMessage': '{0} файлдары тым үлкен және оны қосу мүмкін емес.',
  'ImgDimensionsTooLargeErrorMessage': '{0} суреттің мөлшері тым үлкен. Тараптың  максималды ұйғарынды ұзындығы {1} пиксельді құрайды.',
  'UnsupportedFileTypesErrorMessage': '{0} кеңейтімі бар файлды қосу мүмкін емес. Файл түрі рұқсат етілген тізімге кірмейді.',
};
Localization.UsersBatchImport = {
  'HeadingAddedUsers': '{0}/{1} пайдаланушы қосылды',
};
Localization.UsersRemove = {
  'RemoveSelectedRolesSingleUser': 'Пайдаланушыларда олар таңдап қалған рөлдерді жою',
  'DisabledButtonTooltip': 'Алдымен жойғыңыз келетін пайдаланушыларды және рөлдерді таңдаңыз.',
  'RemoveRoleDefaultText': 'Пайдаланушы рөлін жою',
  'RemoveAllRolesMultipleUsers': '{0} пайдаланушыдан барлық рөлдерді жою',
  'RemoveSpecificRoleMultipleUsers': '{0} пайдаланушының „{1}” рөлін алып тастаңыз',
  'RemoveAllRolesSingleUser': 'Пайдаланушыдан барлық рөлдерді алып тастау',
  'RemoveSelectedRolesMultipleUsers': '{0} пайдаланушыда олар таңдап қалған рөлдерді жою',
  'FromMultipleUsers': '{0} пайдаланушыда',
  'FromSingleUser': '1 пайдаланушыда',
  'RemoveSpecificRoleSingleUser': 'Пайдаланушыдан «{0}» рөлін алып тастаңыз',
};
