/* This file is auto-generated by a tool */
if (!String.prototype.format) {
  String.prototype.format = function() {
    var args = arguments;
    return this.replace(/{(\d+)}/g, function(match, number) {
      return typeof args[number] != 'undefined'
        ? args[number]
        : match
      ;
    });
  };
}
var Localization = Localization || {};
Localization.AddUsers = {
  'NotifyErrorInvitationCanBeResentOnlyToUsersWithEmails': 'Invitation won’t be sent to users without an e-mail address.',
  'UserHasEKoolAndStuudiumBinding': 'User has eKool and Stuudium connection',
  'NotifyErrorChooseMembersToRemove': 'Select the users you want to remove!',
  'NotifyErrorInvitationWasResentOnlyToUsersWithEmails': 'Invitation was sent only to users with an e-mail address.',
  'NotifyWarningNoUsersAdded': 'The users were not added!',
  'UserHasStuudiumBinding': 'User is connected to Stuudium',
  'ValidationErrorWrongEmail': 'Incorrect e-mail address. Only Latin characters are allowed.',
  'NotifyErrorChooseMembersToResendInvitation': 'Select the users you want to reinvite!',
  'UserHasEKoolBinding': 'User is connected to eKool',
  'ErrorChooseStudents': 'Select pupils!',
  'ValidationErrorFormMustHaveFilledRows': 'On one row all fields must be filled!',
};
Localization.AdminCustomerUsers = {
  'ModalTitle': 'Role “{0}” will be removed from the user.',
};
Localization.AdminUsersSearch = {
  'EnterSchoolNameMessage': 'Enter school name',
  'LicensePackageAll': 'All packages',
};
Localization.Annotation = {
  'ErrorMessageAnnotationAlreadyDeleted': 'Failed to edit the annotation, because the annotation was already removed.',
};
Localization.AutoComplete = {
  'SearchingMessage': 'Searching…',
  'ErrorLoadingResultsMessage': 'The results could not be loaded',
  'NoResultsMessage': 'No results',
};
Localization.ChapterExerciseCreate = {
  'NotifyErrorMandatoryChapter': 'Select chapter!',
  'NotifyErrorMandatoryTitle': 'You must enter a title!',
  'NotifyErrorMandatoryKit': 'Select study kit!',
};
Localization.ChapterExercisesIndex = {
  'TooltipTextUserNotInActiveRegisters': 'You have to have at least one course to be able to create a task.',
  'ConfimationDialogAreYouSure': 'Are you sure you want to proceed?',
};
Localization.ChapterIndex = {
  'LinkCopiedSuccessMessage': 'Link copied.',
};
Localization.CouponBatchDetails = {
  'DeleteCouponModalMessage': 'Coupon will be deleted. If a user already has the coupon, they won’t be able to use it anymore.',
};
Localization.CouponCreate = {
  'EnterCustomerNameMessage': 'Enter customer name',
  'PricePerMonthFormat': '{0} month',
  'CustomerTypeSchool': 'School',
  'WarningCouponCountBigFormat': 'Are you sure you want to create {0} coupons?',
  'QuantityMustBeSetError': 'Count must be set.',
  'NoResultsMessage': 'No results',
  'CouponCountMustBeSetError': 'Coupon count must be set.',
  'PackageMustBeSelectedError': 'Package must be set.',
  'CouponValidUntilMustBeSetError': 'Coupon’s valid until date must be set.',
  'CustomerTypeMustBeSelectedError': 'Customer type must be set.',
  'SelectCustomerTypeError': 'Choose customer type.',
  'CustomerTypePrivateUser': 'Private customer',
  'LengthOfValidityMustBeSetError': 'Coupon’s length of validity must be set.',
};
Localization.CreateCustomer = {
  'NoCustomerTypeSelectedError': 'Customer type must be selected.',
};
Localization.CreateSchoolAdminAccount = {
  'PasswordRepeatDifferentError': 'Repeat Password and Password do not match.',
  'RequiredFieldLeftEmptyErrorWithArgs': '{0} is required.',
  'Field': 'Field',
  'PasswordTooShortErrorWithArgs': 'Password has to be at least {0} characters long.',
  'UserNameInvalidEmailWithArgs': '{0} has to be a valid e-mail address.',
};
Localization.Currency = {
  'CurrencyFormatDefault': '{1}{0}',
};
Localization.EditTextExercise = {
  'NeededSpaceRemoval': 'Should have been written as one word',
  'PerformedRemoval': '{0} deleted {1}',
  'NeededSpaceAddition': 'Should have been written as two words',
  'PerformedSpaceRemoval': '{0} written as one word',
  'NeededRemoval': '{0} was not deleted',
  'ExpectedClause': '; should be {0}',
  'NeededReplacement': 'Wasn’t corrected <i>{0} → {1}</i>',
  'EvaluationCorrectly': 'Correctly',
  'PerformedSpaceAddition': '{0} written as two words',
  'EvaluationIncorrectly': 'Incorrectly',
  'NeededAddition': '{0} was not added',
  'PerformedAddition': '{0} added {1}',
  'PerformedReplacement': '{0} replaced <i>{1} → {2}</i>',
};
Localization.ErrorReportModal = {
  'ErrorReportContactInfoExcessiveLength': 'You can enter  up to {0} characters for contact information, you have entered {1} characters.',
  'AddErrorDescription': 'Enter error description!',
  'ErrorReportDescriptionExcessiveLength': 'The error description can be up to {0} characters long, you have entered {1} characters.',
  'ErrorReportCreated': 'Report saved',
};
Localization.ExerciseMenu = {
  'ExerciseToolTipText': 'Task Exercises',
  'ChapterExerciseToolTipText': 'Chapter Exercises',
};
Localization.Exercises = {
  'DragFromGroupTitle': 'Drag the answer from here to a column above',
  'ChangeButtonText': 'Edit',
  'DragHerePlaceholder': 'drag here',
  'SaveButtonText': 'Save',
  'TeachersCommentHeading': 'Comment by {0}',
  'CheckAnswerButtonText': 'Check answer',
  'NoAnswerSelectedByStudent': 'Pupil did not select an answer',
  'ButtonTextShowMyAnswers': 'Show my answers',
  'MethodologicalTextSectionHeading': 'NB! This content item is not visibile to the pupils.',
  'ButtonTextShowStudentsAnswers': 'Show pupil’s answers',
  'FixMistakesButtonText': 'Edit answers',
  'ExerciseOldCommentWarning': 'This is an old comment by {0}. Are you sure you want to send it again?',
  'HideExampleAnswersText': 'Hide example answer',
  'TryAgainButtonText': 'Try again',
  'NoAnswerSelectedByYou': 'You didn’t select an answer',
};
Localization.FoxGraph = {
  'ButtonTextLoad': 'Load',
};
Localization.Global = {
  'SavedNotificationMessage': 'Saved',
  'LoadingContentMessage': 'Loading content…',
  'AjaxErrorSessionExpired': 'User session has expired!',
  'AjaxErrorNoAccess': 'The user has no access to this resource!',
  'AjaxErrorSessionChanged': 'User session has changed, please reload the page!',
  'AjaxErrorNoConnection': 'No connection to server!',
  'DatepickerLanguageCode': 'en',
  'ConfirmationModalQuestion': 'Are you sure you want to do this?',
  'AjaxErrorConcurrency': 'The data have been updated, please reload the page!',
  'AjaxErrorOther': 'Something went wrong :(',
};
Localization.InvoiceRecipient = {
  'ConfirmClearInvoiceRecipientText': 'Do you wish to remove the invoice recipient data?',
};
Localization.JoinRegister = {
  'SuccessfullyJoinedRegister': 'You joined the course!',
};
Localization.JoinSchool = {
  'SuccessfullyJoinedSchool': 'You have joined a school!',
};
Localization.KitAddKitToRegisters = {
  'ChooseRegistersPlaceholder': 'Select',
  'NotifySuccessMessageAddedToSingleRegister': 'Kit add to course',
  'NotifySuccessMessageAddedToMultipleRegisters': 'Kit was added to the course',
};
Localization.KitCreateRegisterFromKit = {
  'NotifyErrorMessageDataNotSaved': 'Failed to save data!',
  'ErrorMessageTeacherNotFound': 'Teacher not found! Please select the teacher from the list!',
  'NotifySuccessMessageDataSaved': 'Data saved!',
};
Localization.KitDetails = {
  'InUseSingleRegister': 'Used in 1 course',
  'InUseRegisters': 'Used in {0} courses',
  'RemoveSuccessMessage': 'The study kit is removed from your study materials.',
};
Localization.LicensingIndex = {
  'LicenseButtonLicenseNUsersText': 'License {0} users',
  'LicenseButtonLicenseOneUserText': 'License 1 user',
  'LicenseButtonText': 'License',
  'LicenseSelectionPlaceHolder': 'Choose license (optional)',
};
Localization.LicensingRemoveLicenses = {
  'ButtonRemoveLicenseNUsersText': 'Remove license from {0} users',
  'LicenseMissing': 'missing license',
  'RemoveLicenseButtonText': 'Remove',
  'ButtonTooltipNoLicenseSelected': 'Choose a license the selected users already have',
  'ChosenLicenseMissing': 'missing selected license',
  'ButtonTooltipNoUsersSelected': 'In order to remove a license, first select users you want to remove a license from',
  'LicenseSelectionPlaceHolder': 'Choose license (optional)',
};
Localization.ManageIndex = {
  'ConfirmationDialog': 'Are you sure you want to proceed?',
};
Localization.ManageLinkLoginConfirmation = {
  'ConfirmationDialog': 'Are you sure you want to proceed?',
};
Localization.MediaGallery = {
  'ExitFullscreen': 'Exit full screen',
  'SendToProjector': 'Send to the projector',
  'ShowFullscreen': 'Show full screen',
};
Localization.OrderDetails = {
  'ConfirmationModalMessage': 'Are you sure you want to proceed?',
  'ReturnToDraftModalBoxTip': 'The order is opened, the school can change the order and confirm it again.',
  'OrderWillBeConfirmedBoxTip': 'The order is being confirmed.',
  'ActionFailedMessage': 'Operation failed.',
  'DeleteOrderCompletelyBoxTip': 'The order will be deleted entirely.',
};
Localization.OrderOrder = {
  'PackageBoxTipText': 'Please make sure that package “{0}” includes the kits you’re interested in. You can view the kits <a href="{1}" class="system-link" target="_blank">here</a>.',
  'ErrorMandatoryPackage': 'Package must be selected.',
  'ConfirmationNeededBoxTipMessageSingle': 'Your order will be reviewed after confirmation because you selected package {0}. Opiq will approve the order after making sure the discount is valid.',
  'ErrorMustAgreeToTermsAndConditions': 'You have to read the terms and conditions and accept them.',
  'ErrorPaymentMethodNotSelected': 'Payment method must be selected.',
  'ErrorMandatoryCountry': 'Select a country.',
  'ErrorChoosePackage': 'First select a package!',
  'SingleMonth': 'month',
  'ErrorMandatoryRegisterCode': 'Enter register code.',
  'DeleteOrderConfimationDialog': 'Are you sure you want to do this?',
  'ErrorPackageNotAvailable': 'The package is not available anymore.',
  'ErrorValidFromMustBeGreaterThanValidUntil': 'Start date must be less than end date.',
  'PackageNameInQuotes': '”{0}”',
  'ErrorMandatoryTown': 'Enter town or city.',
  'ConfimationDialogDeleteLicenseRow': 'Are you sure you want to do this?',
  'ConfirmationNeededBoxTipMessageMultiple': 'Your order will be reviewed after confirmation because you selected package {0}. Opiq will approve the order after making sure the discount is valid.',
  'SchoolConfirmationModalTextWithConfirmationNeededPackage': 'You are confirming the order in the amount of {0}, which will be reviewed by Opiq. Opiq will approve the order after making sure the discount is valid. It may take some time to review your order. All school administrators at this school will receive an order confirmation to their e-mail address.',
  'ErrorMandatoryInvoiceRecipientName': 'Enter invoice recipient name.',
  'PrivateUserConfirmationModalText': 'Before confirming the order, please make sure the selected package includes the kits you are interested in and the period of validity is correct.',
  'ProductSummarySingleMonth': 'Opiq license “{0}” valid for 1 month ({1}–{2}), costing {3}.',
  'MultipleMonths': 'months',
  'Day': 'day',
  'ErrorPaymentScheduleNotCalculated': 'The payment schedule must be calculated.',
  'ErrorMandatoryLicenseValidUntil': 'End date must be selected.',
  'SingleYear': 'year',
  'ErrorMandatoryLicenseValidFrom': 'Start date must be selected.',
  'ProductSummaryMultipleMonths': 'Opiq license “{0}” valid for {1} months ({2}–{3}), costing {4}.',
  'SchoolConfirmationModalText': 'You are confirming the order. You are bound to pay {0} according to the selected payment method. Order confirmation will be sent by e-mail to all your school’s administrators.',
  'OverlappingPendingLicensesWarning': 'License for package “{0}” term {1}–{2} coincides with license for package “{3}” term {4}–{5}!',
  'ErrorMandatoryCounty': 'Enter county.',
  'MultipleYears': 'years',
  'ErrorMandatoryStreetAndHouse': 'Enter street name and house number.',
  'ErrorInvalidEmail': 'Incorrect e-mail address. Only Latin characters are allowed.',
  'ErrorAtLeastOneLicenseMandatory': 'Order must contain at least one row!',
  'DeleteOrderBoxTip': 'The order will be deleted.',
  'ErrorMandatoryZipCode': 'Enter postcode/ZIP code.',
  'ErrorQuantityBiggerThanOne': 'The quantity must be greater than zero.',
  'ErrorMandatoryEmailAddress': 'Enter e-mail address.',
};
Localization.PageHeaderComponent = {
  'GenericLicensesTitle': 'Licenses',
  'GenericFailedImportsTitle': 'Unsuccessful imports',
  'GenericRegistersTitle': 'Courses',
  'GenericStudyProgressTitle': 'Bookmarks',
  'GenericSuccessfulImportsTitle': 'Successful imports',
  'HeaderTitleExerciseNotSavedMessage': 'not saved',
  'GenericInProgressImportsTitle': 'Imports in progress',
  'HeaderTitleExerciseSavedMessage': 'saved',
  'GenericOrdersTitle': 'Orders',
  'GenericTasksTitle': 'Tasks',
};
Localization.PrivateUserKitIndex = {
  'TOCSetCurrentChapter': 'Bookmark chapter',
  'TOCCurrentChapterTooltip': 'This chapter is bookmarked',
  'RemoveSuccessMessage': 'The kit has been removed from your study materials.',
};
Localization.RegisterAdminAddRegister = {
  'RegisterErrorMandatoryKit': 'Select a study kit.',
  'SubmitButtonTextSaveAndSendInvitation': 'Save and send invitations',
  'RegisterErrorMandatoryRegisterName': 'Enter the name of the course.',
};
Localization.RegisterAdminModifyName = {
  'ValidationErrorNotSuccessfulNameModification': 'Failed to edit the name of the course.',
};
Localization.RegisterAdminUpdateKit = {
  'DropdownPlaceholderText': 'Select',
};
Localization.RegisterKitSettings = {
  'StudentsPackageRemovedSuccessfully': 'Adding a license has been suspended!',
  'ConfirmationModalBody': 'Are you sure you want to proceed?',
  'ConfirmationModalBoxTip': 'Joining with code will be suspended. When reactivating the joining with code, a new code is generated, the existing code can no longer be used.',
  'NotifyCodeWasCopied': 'The code was copied',
};
Localization.RegisterKitTaskResults = {
  'SelectListTextAll': 'All',
  'TaskTypesSelectionLabelAllTypes': 'All types',
  'NotifyErrorPeriodHasBeenLimitedToOneYear': 'Must be less than one year.',
  'AppliedTaskTypesCountMessage': '{0} selected',
};
Localization.RegisterLicensing = {
  'ConfirmationModelConfirmText': 'Are you sure you want to add licenses to pupils?',
  'MissingPackagesToShareError': 'The school does not have suitable licenses.',
};
Localization.RegisterListSchoolAdmin = {
  'SearchButtonSearchingTitle': 'Searching…',
  'UserAutoCompletePrompt': 'Enter user’s last name',
  'SearchButtonDefaultTitle': 'Search',
};
Localization.SchoolSettingsConfirmation = {
  'GenericBindingConfirmationDialog': 'Are you sure?',
  'ConfirmationDialogAstraSchoolSameAsStuudiumSchool': 'Are you sure that the Opiq’s school {0} and Stuudium’s school {1} are the same?',
};
Localization.SchoolStudySeasonActivateNextComing = {
  'ConfimationDialogActivateNextComingStudySeason': 'Are you sure you want to end this school year and start the next? This will transfer all the current study groups and courses to the archive. Do you want to proceed?',
};
Localization.Search = {
  'ExercisesSearchTooltipTextUserLacksRegisters': 'You have to have at least one course to be able to create a task.',
};
Localization.SolvingExercise = {
  'HeaderTitleExerciseNotSavedMessage': 'not saved',
  'HeaderTitleExerciseSavedMessage': 'saved',
};
Localization.StudentResultsIndex = {
  'ShowClassAverageButton': 'Show class average',
  'ScoreResultsTooltip': 'This overview covers only tasks with scores as results.',
  'HideClassAverageButton': 'Hide class average',
  'GradeResultsTooltip': 'This overview covers only graded tasks.',
};
Localization.StudentResultsSingleSubject = {
  'NotifyErrorPeriodEndBeforePeriodStart': 'The end of the period must be after the start of the period.',
  'NotifyErrorPeriodLengthLimitation': 'Must be less than one year.',
};
Localization.StudyGroupAdd = {
  'ErrorMandatoryClassNumber': 'Enter the class number.',
  'ErrorNegativeNumber': 'Enter a positive whole number.',
};
Localization.StudyGroupModifyName = {
  'ErrorMandatoryClassNumber': 'Enter the class number.',
  'ErrorNegativeNumber': 'Enter a positive whole number.',
};
Localization.TaskAdd = {
  'NotifySuccessDraftSaved': 'Draft saved.',
  'TextReadThroughTheChapter': 'Read the chapter ”{0}”.',
  'NotifyErrorTooManyExercisesSelected': 'One task cannot include more than {0} exercises.',
  'NotifySuccessTaskAssigned': 'Task is assigned!',
  'NotifyErrorMandatoryExercise': 'You have to select at least one exercise!',
  'NotifyErrorMandatoryRegister': 'Select a course!',
  'NotifyErrorMandatoryTitle': 'You must enter a title!',
  'NotifyErrorMandatoryAddress': 'Select recipient!',
  'NotifyErrorMandatoryDeadline': 'Set a deadline!',
  'ConfimationDialogDeleteDraftTask': 'Are you sure you want to delete the draft?',
  'NotifySuccessTaskDeleted': 'Draft deleted!',
};
Localization.TaskAddExercises = {
  'SelectListPlaceholderText': 'Select',
  'NotifyExercisesAddedSuccessMessage': 'Exercises were added to the draft',
};
Localization.TaskEvaluationIndex = {
  'StatusRejected': 'Sent back',
  'SaveAndDiscloseButtonScore': 'Disclose score',
  'SaveAndDiscloseButtonGrade': 'Disclose mark',
  'TaskRejectedSuccessMessage': 'Task is sent back to the pupil!',
  'SaveAndDiscloseButtonOtherGrade': 'Disclose other rating',
  'SaveAndDiscloseButtonFormativeGrade': 'Disclose formative assessment',
  'StatusNotGraded': 'Not evaluated',
  'StudentMessageHeading': 'Pupil\'s message:',
  'ButtonTextShowMore': 'Show more',
  'ButtonTextShowLess': 'Show less',
  'ScoreNotDisclosableText': 'Can’t calculate the score.',
  'StatusNotDisclosed': 'Not disclosed',
  'DiscloseScoreInfo': 'Disclose the score as a result.',
  'StatusDisclosed': 'Disclosed',
  'SomeAnswersUncheckedToolTipFormat': '{0} answers are not checked',
  'ValidationMaterialBlockHeadingTeacherRecentAddedMaterial': 'Teachers’ recently added material',
};
Localization.TaskReviewIndex = {
  'ButtonTextDiscloseSelected': 'Disclose selected ({0})',
  'ReclaimedAssignedTaskHeading': 'Pupil reclaimed the task',
  'ConfimationDialogDeleteStudentTask': 'Are you sure you want to delete this pupil’s task? If the pupils have already solved exercises and saved their answers, the answers will be deleted.',
  'LinkCopiedSuccessText': 'Link was copied',
  'OnlySubmittedTasksCanBeRejectedErrorMessage': 'Only submitted tasks can be sent back!',
  'ConfimationDialogDeleteTask': 'Are you sure you want to delete this task? If the pupils have already solved exercises and saved their answers, the answers will be deleted.',
  'TaskWillBeDeletedFromeKoolTip': 'The task won’t be deleted in eKool.',
  'DiscloseWarningMessageForMultipleReclaimedTasks': '{0} pupils reclaimed the task.',
  'DiscloseWarningConfirmationForOneReclaimedTask': 'Are you sure you want to disclose the task?',
  'DisclosedTasksCanNotBeDisclosedErrorMessage': 'You don’t have to disclose a task if it’s already disclosed!',
  'TasksRejectedSuccessMessage': 'Tasks have been sent back to the pupils!',
  'TaskWillBeDeletedFromstuudiumTip': 'Task will also be deleted in Stuudium.',
  'DiscloseWarningConfirmationForMultipleReclaimedTasks': 'Are you sure you want to disclose the tasks?',
  'ButtonTextRejectSelected': 'Send back ({0})',
  'DiscloseWarningMessageForOneReclaimedTask': 'Pupil reclaimed the task.',
};
Localization.TaskSolvingIndex = {
  'ExerciseAnswerNotSaved': 'The answers to this exercise are not saved.',
  'AnswerIsTooLong': 'The answer is too long!',
  'ConfirmationDialogSubmitTask': 'Are you sure you want to submit this task?',
  'ChapterNotMarkedRead': 'The chapter is not marked read.',
};
Localization.TaskStatistics = {
  'Tooltip': '{0}<br/>{1}/{2} i.e. {3}% of tasks',
};
Localization.TeacherDesktopTasks = {
  'Deadline': 'Due',
  'ConfirmationDialogRemoveFromDesktop': 'Are you sure you want to remove this task from your home page? You will still find it from the tasks’ list of this course.',
  'Submitted': 'Submitted',
};
Localization.UserDetails = {
  'RemoveLicenseConfirmation': 'Do you want to remove license from user?',
  'InvitationSentMessage': 'Invitation sent!',
};
Localization.UserMaterial = {
  'NoTextEnteredErrorMessage': 'Please enter text.',
  'AddTextHeading': 'Add text',
  'DeleteTextConfirmationMessage': 'Delete text?',
  'FileUploadFailedErrorMessage': 'Error uploading file.',
  'DeleteImageConfirmationMessage': 'Delete image?',
  'AddMaterialHeading': 'Add material',
  'DeleteFileConfirmationMessage': 'Delete file?',
  'SelectFilePrompt': 'Please choose a file.',
  'AddFileHeading': 'Add file',
  'FilesTooLargeErrorMessage': 'Files {0} are too large and cannot be added.',
  'ImgDimensionsTooLargeErrorMessage': 'The image {0} is too large. Images with a maximum of {1} pixels along their longest edge are supported.',
  'UnsupportedFileTypesErrorMessage': 'Files {0} have unsupported type and cannot be added.',
};
Localization.UsersBatchImport = {
  'HeadingAddedUsers': 'Added {0}/{1} users',
};
Localization.UsersRemove = {
  'RemoveSelectedRolesSingleUser': 'Remove selected roles from the user',
  'DisabledButtonTooltip': 'In order to remove a role, first select users and then a role to be removed.',
  'RemoveRoleDefaultText': 'Remove role from users',
  'RemoveAllRolesMultipleUsers': 'Remove all roles from {0} users',
  'RemoveSpecificRoleMultipleUsers': 'Remove the role „{1}” from {0} users',
  'RemoveAllRolesSingleUser': 'Remove all roles from the user',
  'RemoveSelectedRolesMultipleUsers': 'Remove selected roles from {0} users',
  'FromMultipleUsers': 'from {0} users',
  'FromSingleUser': 'from one user',
  'RemoveSpecificRoleSingleUser': 'Remove the role „{0}” from the user',
};
